# Generated by Django 5.2.8 on 2025-11-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0002_alter_supplier_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ingredient Name')),
                ('sku_number', models.CharField(max_length=50, unique=True, verbose_name='SKU Number')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'ml'), (2, 'g')], default=1)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
