# Generated by Django 5.2.8 on 2025-11-11 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+49301234567',             Up to 15 digits is allowed.", regex='^\\+?[\\d]{4,15}$')], verbose_name='Phone number'),
        ),
    ]
